# Generated by Django 4.2.2 on 2023-06-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                
                ('memberID', models.AutoField(primary_key=True, serialize=False)),
                ('batchnum', models.IntegerField()),
                ('firstname', models.CharField(max_length=250)),
                ('midinitial', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('college', models.CharField(max_length=250)),
                ('yearlevel', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('program', models.CharField(max_length=300)),
                ('major', models.CharField(max_length=250)),
                ('acceptdate', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('birthdate', models.DateField()),
                ('civilstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=20)),
                ('religion', models.CharField(max_length=250)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Requirements_list',
            fields=[
                
                ('reqs_listID', models.AutoField(primary_key=True, serialize=False)),
                ('reqs_requirements', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Requirements_list',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                
                ('reqsID', models.AutoField(primary_key=True, serialize=False)),
                ('reqs_listID', models.ForeignKey(db_column='reqs_listID', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='scholars.requirements_list')),
                ('memberID', models.ForeignKey(db_column='memberID', on_delete=django.db.models.deletion.CASCADE, to='scholars.members')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Allowances',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
               
                ('gradeID', models.AutoField(primary_key=True, serialize=False)),
                ('memberID', models.ForeignKey(db_column='memberID', on_delete=django.db.models.deletion.CASCADE, to='scholars.members')),
                ('yearlevel', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('semester', models.CharField(choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem')], max_length=20)),
                ('course', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('unit', models.IntegerField()),
                ('grades', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Allowances',
            fields=[
                
                ('allowanceID', models.AutoField(primary_key=True, serialize=False)),
                ('memberID', models.ForeignKey(db_column='memberID', on_delete=django.db.models.deletion.CASCADE, to='scholars.members')),
                ('yearlevel', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('semester', models.CharField(choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem')], max_length=20)),
                ('month', models.CharField(choices=[('1st Month', '1st Month'), ('2nd Month', '2nd Month'), ('3rd Month', '3rd Month'), ('4th Month', '4th Month'), ('5th Month', '5th Month')], max_length=20)),
                ('date_received', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Allowances',
            },
        ),
    ]
